### ISSUE TITLE
Errors throwing for existing documents - TypeError: Cannot call method 'toString' of undefined

### ISSUE THREAD

**Issue by lb-** [todda00/meteor-friendly-slugs#1]
Hi, I just tried out this package (brilliant idea!), however I am getting this error.

The slug seems to be working, except that every time this error comes up on the server & client, it updates (I have even checked the field via Meteor Shell) but keeps throwing the errors below.

However (with updateSlug to true) when I create a NEW document, I get no errors and slug works, even when updating the related field ('title') in this case.

I would like to use this with a collection that is already in place, so please advise what I can do to help resolve this issue.
### /collections/campaigns.js

_Client & Server_

``` js
db.Campaigns = new Mongo.Collection('campaigns');
// using simple schema to define a schema + I have put the field 'slug' as an optional string in the schema
db.Campaigns.attachSchema(Schemas.Campaigns);
// using collection helpers to generate some other fields
db.Campaigns.helpers(Schemas.campaignHelpers);
db.Campaigns.friendlySlugs({
  // I have tried the 'title' field first as this is the ideal but just tried to at least get it working with _id field, but same errors, I thought that maybe if 'title' was empty it would fail but I also checked my collection and all docs have the 'title' field
  slugFrom: '_id',
  slugField: 'slug',
  distinct: true,
  updateSlug: true,
});
```
### Error result (server console)

``` bash
I20150205-07:42:11.412(10)? Exception while invoking method 'updateDocument' TypeError: Cannot call method 'toString' of undefined
I20150205-07:42:11.413(10)?     at slugify (packages/todda00:friendly-slugs/slugs.coffee:95:15)
I20150205-07:42:11.413(10)?     at runSlug (packages/todda00:friendly-slugs/slugs.coffee:43:16)
I20150205-07:42:11.413(10)?     at Object.<anonymous> (packages/todda00:friendly-slugs/slugs.coffee:38:7)
I20150205-07:42:11.413(10)?     at packages/matb33:collection-hooks/update.js:41:1
I20150205-07:42:11.414(10)?     at Array.forEach (native)
I20150205-07:42:11.414(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150205-07:42:11.414(10)?     at packages/matb33:collection-hooks/update.js:40:1
I20150205-07:42:11.414(10)?     at Array.forEach (native)
I20150205-07:42:11.414(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150205-07:42:11.414(10)?     at Object.fields (packages/matb33:collection-hooks/update.js:39:1)
```
## Error result (client)

``` console
Exception in delivering result of invoking 'updateDocument': Error: Internal server error [500]
    at _.extend._livedata_result (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:4925:23)
    at onMessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:3723:12)
    at http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:2717:11
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at _.extend._launchConnection.self.socket.onmessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:2716:11)
    at REventTarget.dispatchEvent (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:156:22)
    at SockJS._dispatchMessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:1141:10)
    at SockJS._didMessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:1199:18)
    at WebSocket.SockJS.websocket.that.ws.onmessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:1346:17)
```

**Comment by todda00** [comment]
I hadn't done any testing with adding the package with collections with existing items, I re-configured some things so this will work now. 

It will now create a slug during an update even if the slugFrom field has not changed. If you don't want the slug to be created in this situation, set createOnUpdate to false.

Please let me know if the latest version (0.1.1) is working for you.

FYI - I am using simple schema and do not need to register the slug field in the schema for it to work - it is created in an update hook which simple schema does not restrict. Let me know if for some reason you do need to register the field(s) in simple schema.

**Comment by lb-** [comment]
Hi,

Still getting the errors.

Regarding the simple schema, with debugging on I am getting this issue with updates

```
I20150206-14:49:41.101(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs", which is not allowed by the schema
I20150206-14:49:41.101(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs.slug", which is not allowed by the schema
I20150206-14:49:41.101(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs.slug.base", which is not allowed by the schema
I20150206-14:49:41.101(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs.slug.index", which is not allowed by the schema
I20150206-14:49:41.101(10)? SimpleSchema.clean: filtered out value that would have affected key "slug", which is not allowed by the schema
I20150206-14:49:41.113(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs", which is not allowed by the schema
I20150206-14:49:41.113(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs.slug", which is not allowed by the schema
I20150206-14:49:41.113(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs.slug.base", which is not allowed by the schema
I20150206-14:49:41.114(10)? SimpleSchema.clean: filtered out value that would have affected key "friendlySlugs.slug.index", which is not allowed by the schema
I20150206-14:49:41.114(10)? SimpleSchema.clean: filtered out value that would have affected key "slug", which is not allowed by the schema
```

Adding this to my schema stopped the logs from appearing.

```
friendlySlugs: {
    type: Object,
    blackbox: true,
  },
  slug: {
    type: String,
    optional: true,
  },
```

**Comment by todda00** [comment]
Ok, so as long as the collection definition is in a file the server can get to, the update will happen and SimpleSchema will not strip it out, it will only be stripped from a client side. If you really don't want to see the debug messages or need the update to happen at the client level right away, then adding the fields to the schema as you have done is the right thing to do.

As far as the real error, I think your update is running twice for some reason, once without the title, and once with the title. I do notice you have 2 sets of SimpleSchema updates running, telling me its running twice. I will need to do some more testing to see if I can fix the package to not get tripped up in these situations.

I haven't used collection helpers yet - perhaps this is causing the update to happen twice?

**Comment by todda00** [comment]
Try the latest, 0.1.2, let me know if that does any better.

**Comment by lb-** [comment]
Hi,

still getting the same errors

## Client

``` js
Exception in delivering result of invoking 'updateDocument': Error: Internal server error [500]
    at _.extend._livedata_result (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:4925:23)
    at onMessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:3723:12)
    at http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:2717:11
    at Array.forEach (native)
    at Function._.each._.forEach (http://localhost:3000/packages/underscore.js?0a80a8623e1b40b5df5a05582f288ddd586eaa18:156:11)
    at _.extend._launchConnection.self.socket.onmessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:2716:11)
    at REventTarget.dispatchEvent (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:156:22)
    at SockJS._dispatchMessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:1141:10)
    at SockJS._didMessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:1199:18)
    at WebSocket.SockJS.websocket.that.ws.onmessage (http://localhost:3000/packages/ddp.js?41b62dcceb3ce0de6ca79c6aed088cccde6a44d8:1346:17)
```

## Server

``` bash
I20150210-07:58:34.079(10)? Exception while invoking method 'updateDocument' TypeError: Cannot call method 'toString' of undefined
I20150210-07:58:34.079(10)?     at slugify (packages/todda00:friendly-slugs/slugs.coffee:95:15)
I20150210-07:58:34.079(10)?     at runSlug (packages/todda00:friendly-slugs/slugs.coffee:43:16)
I20150210-07:58:34.080(10)?     at Object.<anonymous> (packages/todda00:friendly-slugs/slugs.coffee:38:7)
I20150210-07:58:34.080(10)?     at packages/matb33:collection-hooks/update.js:41:1
I20150210-07:58:34.080(10)?     at Array.forEach (native)
I20150210-07:58:34.080(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150210-07:58:34.080(10)?     at packages/matb33:collection-hooks/update.js:40:1
I20150210-07:58:34.080(10)?     at Array.forEach (native)
I20150210-07:58:34.080(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150210-07:58:34.080(10)?     at Object.fields (packages/matb33:collection-hooks/update.js:39:1)
I20150210-07:58:34.136(10)? Exception while invoking method 'updateDocument' TypeError: Cannot call method 'toString' of undefined
I20150210-07:58:34.136(10)?     at slugify (packages/todda00:friendly-slugs/slugs.coffee:95:15)
I20150210-07:58:34.136(10)?     at runSlug (packages/todda00:friendly-slugs/slugs.coffee:43:16)
I20150210-07:58:34.136(10)?     at Object.<anonymous> (packages/todda00:friendly-slugs/slugs.coffee:38:7)
I20150210-07:58:34.137(10)?     at packages/matb33:collection-hooks/update.js:41:1
I20150210-07:58:34.137(10)?     at Array.forEach (native)
I20150210-07:58:34.137(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150210-07:58:34.137(10)?     at packages/matb33:collection-hooks/update.js:40:1
I20150210-07:58:34.137(10)?     at Array.forEach (native)
I20150210-07:58:34.137(10)?     at Function._.each._.forEach (packages/underscore/underscore.js:105:1)
I20150210-07:58:34.137(10)?     at Object.fields (packages/matb33:collection-hooks/update.js:39:1)
```

**Comment by todda00** [comment]
Ok, I worked out a lot of bugs with this last version (0.1.3)
If it still doesn't work, please add the debug:true option and provide the console logs for both client and server.

**Comment by lb-** [comment]
Hey. Latest version is working brilliantly. Thank you. I'll let you know if I run into that issue or another in the future. Really appreciate all your hard work. Let me know if you need a hand with something on this repo

**Comment by todda00** [comment]
Wonderful! Glad its working for you now.
